pull_request_rules:
  - name: assign and label scala-steward's PRs
    conditions:
      - author=github-actions
    actions:
      assign:
        users: [cric96]
      label:
        add: [dependency-update]
  - name: merge scala-steward's PRs
    conditions:
      - author=github-actions
      - status-success=Build
    actions:
      merge:
        method: squash
        strict: true
