queue_rules:
  - name: default
    queue_conditions:
      - author=cric96
      - status-success=Build
    merge_conditions:
      # Conditions to get out of the queue (= merged)
      - author=cric96
      - status-success=Build
    merge_method: merge

pull_request_rules:
  - name: assign and label scala-steward's PRs
    conditions:
      - author=cric96
    actions:
      assign:
        users: [cric96]
      label:
        add: [dependency-update]
  - name: merge scala-steward's PRs
    conditions: []
    actions:
      queue:
