name: Build

on:
  push:
    tags: ['v*']
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install python dependencies
      run: python -m pip install -r requirements.txt
    - name: Run test and coverage
      run: sbt clean coverage +test coverageReport
    - name: Publish on Codacy
      uses: codacy/codacy-coverage-reporter-action@v1
      with:
        project-token: ${{ secrets.CODACY_API_TOKEN }}
        coverage-reports: target/scala-2.13/coverage-report/cobertura.xml

  Github-Release:
    runs-on: ubuntu-latest
    needs: [Test]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - name: Create a release
      uses: softprops/action-gh-release@v1

  Publish:
    runs-on: ubuntu-latest
    needs: [Github-Release]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        with:
          java-version: '11'
        uses: actions/setup-java@v2
      - name: Release packages
        run: sbt clean ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}

  Microsite:
    runs-on: ubuntu-latest
    needs: [ Github-Release ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        with:
          java-version: '11'
        uses: actions/setup-java@v2
      - name: Make site and scala doc
        run: sbt makeSite
      - name: Publish site
        run: sbt publishToGitHubPages