name: Build

on:
  push:
  pull_request:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Virtual desktop
      run: export DISPLAY=':99.0'; Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    - name: Install python dependencies
      run: python -m pip install -r requirements.txt
    - name: Run test and coverage
      run: sbt clean coverage +test coverageReport
    ### Release part
    - name: Publish on Codacy
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      uses: codacy/codacy-coverage-reporter-action@v1
      with:
        project-token: ${{ secrets.CODACY_API_TOKEN }}
        coverage-reports: target/scala-2.13/coverage-report/cobertura.xml
    - name: Tag release
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      run: sbt ciReleaseTagNextVersion
    ### If completed, this workflow trigger deploy.yaml