name: Deploy

on:
  push:


jobs:
  Microsite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Set up JDK 11
        with:
          java-version: '11'
          distribution: 'adopt'
        uses: actions/setup-java@v2
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.88.1'
      - name: Make site and scala doc
        run: sbt makeSite
      - name: Publish site
        run: sbt publishToGitHubPages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
